### ISSUE TITLE
Get error when trying to run a for loop with function searchSubtitles() in inside.

### ISSUE THREAD

**Issue by vucuong12** [gtuk/yifysubs#1]
In the file examples/singleSubtitle.js, I tried to a little bit modify it:

var yifysubs = require("../");

for (var i = 0; i < 200; i++)
{
    yifysubs.searchSubtitles( 'All', 'tt3816458', function(i, result){
        console.log(result);
    });
}

-> about 160-170 requests were successful (there were about 160-170 result were printed out), but then there was an error like this:

D:\project\yifysubs\yify.js:16
            _.each(data.subs, function(languages) {
                       ^
TypeError: Cannot read property 'subs' of undefined
    at Request._callback (D:\project\yifysubs\yify.js:16:24)
    at self.callback (D:\project\yifysubs\node_modules\request\request.js:123:22)
    at Request.emit (events.js:107:17)
    at ClientRequest.self.clientErrorHandler (D:\project\yifysubs\node_modules\request\request.js:244:10)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

-> It is really appreciated if you can fix it?
Thank you in advance :)

**Comment by gtuk** [comment]
I will take a deeper look on this issue in the weekend. Thanks for reporting

**Comment by gtuk** [comment]
@vucuong12 please test the latest pushes in the master branch
